// User-supplied serving illustrations; presentation and accompaniments may vary.
export const menuPhotos = {
  brooklyn: 'Scrambled egg, turkey bacon and cheese on a seeded bagel.',
  avocado: 'A seeded breakfast bagel with fried egg, avocado, turkey bacon and cheese.',
  dawn: 'An open bagel with cream cheese and crispy turkey bacon.',
  cream: 'A seeded bagel generously spread with plain cream cheese.',
  scallion: 'A seeded bagel filled with scallion cream cheese.',
  jelly: 'An open bagel spread with butter and red fruit jelly.',
  balt: 'A bagel sandwich layered with avocado, lettuce, tomato and turkey bacon.',
  tuna: 'Toasted bread filled with tuna salad, melted cheddar, lettuce and tomato.',
  smash: 'A beef burger with melted cheese on a toasted bun.',
  pancake: 'A stack of golden pancakes with butter and syrup.',
  'pancake-eggs': 'Golden pancakes served with two fried eggs.',
  waffles: 'Golden waffles photographed with berries and cream.',
  'waffles-eggs': 'Golden waffles served with two fried eggs.',
  toast: 'Thick French toast photographed with syrup, berries and whipped cream.',
  crepes: 'Folded crepes photographed with fruit and chocolate drizzle.',
  coffee: 'Dark coffee pouring into a black cup on a black studio background.',
  tea: 'Amber black tea pouring into a glass cup on a black studio background.',
  lipton: 'Amber black tea pouring into a glass cup, photographed on black.',
  latte: 'A milk splash from a stoneware cup with roasted coffee beans in motion, on black.',
  'samosa-chaat': 'Samosa chaat covered with chickpeas, yogurt and chutneys.',
  chana: 'Spicy chickpea chaat with chopped vegetables, herbs and lemon.',
  shami: 'A shami patty and egg burger with salad in a sesame bun.',
  fries: 'Golden fries dusted with masala and fresh herbs.',
  gol: 'Six crisp gol gappay shells with filling and two accompanying sauces.',
  samosa: 'Golden triangular samosas with a bowl of green chutney.',
  pakora: 'Crisp vegetable pakoras served with green chutney.',
  kheer: 'Creamy rice pudding finished with chopped nuts.',
  rasmalai: 'Soft rasmalai rounds in sweet milk, garnished with pistachios.',
  adeni: 'Adeni milk tea pouring into a glass with steam and spices on black.',
  cardamom: 'Milky cardamom chai splashing from a cup, green pods in motion, on black.',
  masala: 'Milky masala chai in motion with cardamom pods, photographed on black.',
  karak: 'Karak chai pouring into a glass with steam, cinnamon and cardamom on black.',
  doodh: 'Creamy doodh pati chai mid-splash with cardamom, on a black studio background.',
  nutty: 'A creamy peanut smoothie photographed with a whipped topping and nuts.',
  banana: 'A pale banana and nut smoothie with banana slices.',
  berry: 'A deep pink berry smoothie with raspberries, blueberries and strawberries.',
  strawberry: 'A strawberry banana smoothie with fresh fruit alongside.',
  mango: 'A golden mango smoothie with mango pieces and mint.',
  detox: 'Fresh green juice with cucumber, leafy greens and ginger.',
  beet: 'Ruby red beet juice with beetroot, carrot and lemon alongside.',
  tropical: 'Golden pineapple and carrot juice with ginger and lemon.',
  orange: 'A glass of fresh orange juice beside cut oranges.',
  custom: 'A selection of colourful fruit and vegetable juices with fresh ingredients.',
  muffin: 'A golden blueberry muffin in a paper case.',
  danish: 'A flaky fruit Danish finished with a light icing drizzle.',
  cinnamon: 'A spiral cinnamon bun with a drizzle of icing.',
  cookie: 'A golden cookie studded with chocolate chips.',
};
